// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebrpuitgribvmstqosku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVicnB1aXRncmlidm1zdHFvc2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTM3MDgsImV4cCI6MjA2NjQyOTcwOH0.Vu-tcqV2HrqFUV4N0BZI2-92nnZUicTFgRDaHEyquP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);